/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.create;

import controller.MoradorController;
import controller.PessoaController;
import controller.ProprietarioController;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;
import model.ComboItem;
import model.Pessoa;

/**
 *
 * @author vinic
 */
public class CadastroMoradorOuProprietarioView extends javax.swing.JFrame {
    private MoradorController moradorController;
    private ProprietarioController proprietarioController;
    private PessoaController pessoaController;

    public CadastroMoradorOuProprietarioView() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // pra não fechar todo o programa ao clicar no X
        this.moradorController = new MoradorController();
        this.proprietarioController = new ProprietarioController();
        this.pessoaController = new PessoaController();

        try {
            carregarComboPessoa(); // carrega o combo já na abertura da tela
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar pessoas: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void carregarComboPessoa() throws SQLException {
        List<Pessoa> pessoas = pessoaController.listarTodos();
        cmbPessoa.removeAllItems();

        pessoas.forEach(p -> 
            cmbPessoa.addItem(new ComboItem(p.getId(), p.getNome() + " - " + p.getCpf()))
        );
    }

    public void selecionarPessoaNoCombo(ComboItem item) {
        IntStream.range(0, cmbPessoa.getItemCount())
            .filter(i -> ((ComboItem) cmbPessoa.getItemAt(i)).getId() == item.getId())
            .findFirst()
            .ifPresent(cmbPessoa::setSelectedIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrarMorador = new javax.swing.JButton();
        cmbPessoa = new javax.swing.JComboBox();
        btnCadastrarProprietario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 245, 247));

        btnCadastrarMorador.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnCadastrarMorador.setForeground(new java.awt.Color(66, 66, 66));
        btnCadastrarMorador.setText("Cadastrar Morador");
        btnCadastrarMorador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(110, 158, 158), 3, true));
        btnCadastrarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMoradorActionPerformed(evt);
            }
        });

        cmbPessoa.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        cmbPessoa.setForeground(new java.awt.Color(66, 66, 66));
        cmbPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPessoaActionPerformed(evt);
            }
        });

        btnCadastrarProprietario.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        btnCadastrarProprietario.setForeground(new java.awt.Color(66, 66, 66));
        btnCadastrarProprietario.setText("Cadastrar Proprietario");
        btnCadastrarProprietario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(110, 158, 158), 3, true));
        btnCadastrarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProprietarioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 66, 66));
        jLabel5.setText(" Atribuição de Pessoa");

        jButton1.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(110, 158, 158), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrarMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCadastrarProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cmbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMoradorActionPerformed
        try {
            ComboItem itemSelecionado = (ComboItem) cmbPessoa.getSelectedItem();
            if (itemSelecionado == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma pessoa.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idPessoa = itemSelecionado.getId();

            // Verificar se já é morador
            if (moradorController.pessoaJaEhMorador(idPessoa)) {
                JOptionPane.showMessageDialog(this, "Esta pessoa já é um morador!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return; // Para não continuar o cadastro
            }

            Pessoa pessoa = pessoaController.buscarPorId(idPessoa);
            int idMorador = moradorController.cadastrarMorador(pessoa);

            JOptionPane.showMessageDialog(this, "Morador cadastrado com sucesso!");

            Object[] opcoes = {"Sim", "Não"};
            int opcao = JOptionPane.showOptionDialog(this,
                "Deseja vincular este morador a uma residência?",
                "Vincular Residência",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);

            if (opcao == JOptionPane.YES_OPTION) {
                new VincularMoradorView(null, idMorador).setVisible(true);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar morador: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCadastrarMoradorActionPerformed

    private void cmbPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPessoaActionPerformed

    private void btnCadastrarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProprietarioActionPerformed
        try {
            ComboItem itemSelecionado = (ComboItem) cmbPessoa.getSelectedItem();
            if (itemSelecionado == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma pessoa.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idPessoa = itemSelecionado.getId();

            // Verifica se já é proprietário
            if (proprietarioController.pessoaJaEhProprietario(idPessoa)) {
                JOptionPane.showMessageDialog(this, "Esta pessoa já é proprietária.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Pessoa pessoa = pessoaController.buscarPorId(idPessoa);

            proprietarioController.cadastrarProprietario(pessoa);

            JOptionPane.showMessageDialog(this, "Proprietário cadastrado com sucesso!");
            // limparCampos(); // se quiser limpar campos depois

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar proprietário: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCadastrarProprietarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMoradorOuProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMoradorOuProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMoradorOuProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMoradorOuProprietarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroMoradorOuProprietarioView().setVisible(true)); // Refatorado para lambda
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarMorador;
    private javax.swing.JButton btnCadastrarProprietario;
    private javax.swing.JComboBox cmbPessoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
